repos:
-   repo: local
    hooks:
    -   id: ruff format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]
    -   id: ruff check
        name: ruff check
        entry: ruff check
        language: system
        types: [python]
    -   id: pydoclint
        name: pydoclint
        entry: pydoclint
        language: system
        types: [python]
    -   id: pyrefly
        name: pyrefly
        entry: pyrefly check
        language: system
        types: [python]
